name: drunk_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/photo/photo2.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:

  uses-material-design: true

  assets:
    - assets/audio/geiger_short.mp3
    - assets/audio/geiger_long.mp3
    - assets/photo/photo1.png
    - assets/photo/photo2.png


